### ISSUE TITLE
websocket问题

### ISSUE THREAD

**Issue by dhdbuwl** [mixstart/mixphp#14]
按照官方文档中的客户端代码测试websocket服务，发现以下问题：
刷新客户端页面后，再次发送join room那条命令，后台会报错。

我看了下chrome的console日志，发现刷新页面时，并没有调用onclose关闭连接，不知道服务端是不是也没有关闭连接，导致join room时的广播出问题了，之前的连接还存在，并被认为是一个无效的socket连接。

**Comment by onanying** [comment]
下载 master 版本，这个问题已经解决

**Comment by onanying** [comment]
是这样的，ServiceController 中 onClose 方法，由于我只 unset 了数据，但没有把 $webSocket->fds[$fd] 这个节点 unset ，所以留下了一个不断增加的空数组，只需要加一句 unset($webSocket->fds[$fd]); 即可，多谢反馈，我会在 master 更新这个 WebSocket 的范例。
