### ISSUE TITLE
控制器继承问题

### ISSUE THREAD

**Issue by dhdbuwl** [mixstart/mixphp#16]
官方文档《session》一节

> 效验Session：
> 
> 需创建一个 BaseController 控制器，然后其他控制器继承该控制器。
> 
> ```
> // BaseController 的初始化事件
> public function onInitialize()
> {
>     parent::onInitialize(); // TODO: Change the autogenerated stub
>     $userinfo = \Mix::app()->session->get('userinfo');
>     if (empty($userinfo)) {
>         \Mix::app()->response->redirect('/');
>         \Mix::app()->response->send();
>         \Mix::app()->end();
>     }
> }
> ```

BaseController只能放在子类的同级目录么？
我在apps\index\下新建目录base\，BaseControoler放在该目录下是否可行？ 我试了下，发现子类无法继承到该父类，是我方式不对么？还是有更好的解决方案

**Comment by dhdbuwl** [comment]
已解决，是我的use语句没写完整

**Comment by onanying** [comment]
哥们，阔以哦，帮忙多发现发现bug，要不要入群：MixPHP技术交流A群：284806582
