### ISSUE TITLE
mix-httpd下的http_user_agent问题

### ISSUE THREAD

**Issue by fenghoer** [mixstart/mixphp#20]
我在mix-httpd下打印出来的的\Mix::app->request->server()里没有http_user_agent，这个信息是丢失了吗，还是要用其它方式去取

**Comment by fenghoer** [comment]
呖 不是下划线，差点又进坑

**Comment by onanying** [comment]
对，\Mix::app()->request->header('user-agent')，mix 里 server 超时变量分为了 header 与 server 两个，为了与 swooleServer 兼容。
