### ISSUE TITLE
迁移到1.0.3，mix\swoole\Response::FORMAT_JSON

### ISSUE THREAD

**Issue by fenghoer** [mixstart/mixphp#21]
![image](https://user-images.githubusercontent.com/6119494/39110530-112e3b46-4704-11e8-895e-97dcc305bd6f.png)
迁移到1.0.3的过程中，composer.json中去掉了以下的配置
![image](https://user-images.githubusercontent.com/6119494/39110558-348d09c8-4704-11e8-88ae-96a5d370e4da.png)
然后就报了mix\swoole\Response不存在的错误。这个配置不应该去掉吗？

**Comment by onanying** [comment]
v1.0.3 的源码，使用了 composer 独立了框架核心，你这样操作：
1. 把 composer.json 修改为 https://github.com/mixstart/mixphp/blob/master/composer.json 的内容。
2. 使用 composer update 命令，该命令会拉取新版本的核心。
3. 你的旧版本的 mixphp 目录就没有使用到了，可以删除。
