### ISSUE TITLE
在mix-crontab下取 \Mix::app()->request->server()的问题。

### ISSUE THREAD

**Issue by zhyfor** [mixstart/mixphp#23]
如题，在mix-crontab下的控制器中取\Mix::app()->request->server()时，报以下错：
Call to undefined method mix\console\Request::server()
Error code 0

在crontab下取$_SERVER的正确方式是什么？

**Comment by onanying** [comment]
mix-crontab 是 Console 应用，也就是 CLI 模式下的命令行程序。
Console 应用没有 request 组件，所以会报这个错误。
另外：CLI 下的 $_SERVER 全部是一些环境变量，没有 IP 地址这些信息，所以不计划在框架封装获取方法。
