### ISSUE TITLE
gpl协议，不利于推广

### ISSUE THREAD

**Issue by realcontra** [mixstart/mixphp#24]
框架不错，希望能一直保持轻量高效的特点，只是gpl协议有点不利于推广。基于框架无法搞商业应用，这个就把很多潜在用户拒之门外了。能否考虑采用更加开放的开源协议？

**Comment by nottellyou** [comment]
我朋友弄的fastadmin直接就是mit协议。

**Comment by sendee** [comment]
其实PHP协议蛮好. 主要是要允许自由使用, 同时又避免别人开分支而不做贡献, 不反馈给上游主干分支.

**Comment by realcontra** [comment]
就是这个意思，作为操作系统gpl没问题，但是作为一个通用框架，gpl有点太严格了，php 协议+1

**Comment by onanying** [comment]
已修改为 Apache-2.0，大家随意整。

**Comment by realcontra** [comment]
赞！
