### ISSUE TITLE
mysql连接超时，报管道错误问题

### ISSUE THREAD

**Issue by lizongdi** [mixstart/mixphp#26]
当my.cnf配置中俩个参数wait_timeout,interactive_timeout设置很小的时候，且使用mix长连接组件PdoPersistent、其中的参数"persistentTime" 设置小于wait_timeout,interactive_timeout，会报以下的错误
 mix\client\BasePdo::disconnect(): send of 5 bytes failed with errno=32 Broken pipe

**Comment by onanying** [comment]
已经解决该问题，下一个版本 v1.0.7 你将能看到。
