### ISSUE TITLE
Uncaught mix\exceptions\ErrorException: Undefined index: host in /data/mix/vendor/mixstart/framework/swoole/HttpServer.php:95

### ISSUE THREAD

**Issue by fenghoer** [mixstart/mixphp#27]
mixphp运行了一段时间（约有两个星期），在error.log中看到报下面的错误，一天内有几十条左右。检查了一下配置未发现问题。
详细错误日志信息如下：
[time] 2018-05-15 00:27:12
[code] 1
[message] Uncaught mix\exceptions\ErrorException: Undefined index: host in /export/webapps/zepra-api/vendor/mixstart/framework/swoole/HttpServer.php:95
Stack trace:
#0 /export/webapps/zepra-api/vendor/mixstart/framework/swoole/HttpServer.php(95): mix\web\Error::appError(8, 'Undefined index...', '/export/webapps...', 95, Array)
#1 {main}
  thrown
[type] mix\exceptions\ErrorException
[file] /export/webapps/zepra-api/vendor/mixstart/framework/swoole/HttpServer.php line 95
[trace] #0 [internal function]: mix\web\Error::appShutdown()
#1 {main}
$_SERVER
(
    [MANPATH] => +HOME/man
    [LESS_TERMCAP_mb] => [01;31m
    [HOSTNAME] => ip-10-240-10-133
    [LESS_TERMCAP_md] => [01;38;5;208m
    [LESS_TERMCAP_me] => [0m
    [SHELL] => /bin/bash
    [TERM] => xterm
    [HISTSIZE] => 1000
    [SSH_CLIENT] => 52.220.115.23 45478 22
    [EC2_AMITOOL_HOME] => /opt/aws/amitools/ec2
    [GOBIN] => /home/synative/gopath/bin
    [PYTHON_INSTALL_LAYOUT] => amzn
    [LESS_TERMCAP_ue] => [0m
    [SSH_TTY] => /dev/pts/1
    [USER] => synative
    [LS_COLORS] => rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=01;05;37;41:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=01;36:*.au=01;36:*.flac=01;36:*.mid=01;36:*.midi=01;36:*.mka=01;36:*.mp3=01;36:*.mpc=01;36:*.ogg=01;36:*.ra=01;36:*.wav=01;36:*.axa=01;36:*.oga=01;36:*.spx=01;36:*.xspf=01;36:
    [EC2_HOME] => /opt/aws/apitools/ec2
    [LESS_TERMCAP_us] => [04;38;5;111m
    [PATH] => /export/jdk/bin:/export/jdk/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/opt/aws/bin:/usr/local/go/bin:/usr/local/go/pkg/tool/linux_amd64:/Golang/bin:/home/synative/.local/bin:/home/synative/bin:/usr/local/go/bin
    [MAIL] => /var/spool/mail/synative
    [PWD] => /export/webapps/zepra-api
    [JAVA_HOME] => /export/jdk
    [GOARCH] => amd64
    [AWS_CLOUDWATCH_HOME] => /opt/aws/apitools/mon
    [LANG] => en_US.UTF-8
    [HISTCONTROL] => ignoredups
    [HOME] => /home/synative
    [SHLVL] => 2
    [GOROOT] => /usr/local/go
    [AWS_PATH] => /opt/aws
    [GOOS] => linux
    [AWS_AUTO_SCALING_HOME] => /opt/aws/apitools/as
    [LOGNAME] => synative
    [CVS_RSH] => ssh
    [GOPKG] => /usr/local/go/pkg/tool/linux_amd64
    [SSH_CONNECTION] => 52.220.115.23 45478 10.240.10.133 22
    [CLASSPATH] => .:/export/jdk/lib/dt.jar:/export/jdk/lib/tools.jar:/export/jdk/jre/lib/rt.jar
    [AWS_ELB_HOME] => /opt/aws/apitools/elb
    [LESSOPEN] => ||/usr/bin/lesspipe.sh %s
    [GOPATH] => /home/synative/gopath
    [LESS_TERMCAP_se] => [0m
    [_] => bin/mix-httpd
    [PHP_SELF] => bin/mix-httpd
    [SCRIPT_NAME] => bin/mix-httpd
    [SCRIPT_FILENAME] => bin/mix-httpd
    [PATH_TRANSLATED] => bin/mix-httpd
    [DOCUMENT_ROOT] => 
    [REQUEST_TIME_FLOAT] => 1525922247.7231
    [REQUEST_TIME] => 1525922247
    [argv] => Array
        (
            [0] => bin/mix-httpd
            [1] => service/restart
            [2] => -d
        )

    [argc] => 3
)
$_GET
(
)
$_POST
(
)

**Comment by onanying** [comment]
这是因为有些非法http请求，没有指定 host ，已经修复，详情：https://github.com/mixstart/framework/commit/25236d828b868f426e0817f127b3db8fa9eab53f
