### ISSUE TITLE
数据库事务操作报如下错误：PDO::beginTransaction(): send of 22 bytes failed with errno=32 Broken pipe

### ISSUE THREAD

**Issue by jiajiale** [mixstart/mixphp#28]
直接调用beginTransaction，会出现_pdo不存在，将源码中的beginTransaction方法内加上$this->autoConnect();后，经常出现PDO::beginTransaction(): send of 22 bytes failed with errno=32 Broken pipe错误和There is no active transaction这个错误，请问是不是我哪里写法不对

**Comment by onanying** [comment]
_pdo不存在是个bug，已经修复， https://github.com/mixstart/framework/commit/e09380063fafe46f6e5071d3b4b37d279a080274  ，send of 22 bytes failed with errno=32 Broken pipe 应该是长连接的bug，这个有其他朋友反馈，也修复了，下一版本能看到，There is no active transaction 不太清楚原因。
