### ISSUE TITLE
如何使topthink/think-orm保持长连接呢？

### ISSUE THREAD

**Issue by Shandawei** [mixstart/mixphp#30]
其他框架可以使think-orm保持长连接，但是在mixphp的项目里，设置初始化Db后每次还是需要连接。
[参考](https://www.easyswoole.com/Manual/2.x/Cn/_book/Database/think_orm.html)
那在mixphp中该如何实现类似的功能呢？

**Comment by onanying** [comment]
mix有专门的mysql/redis长连接组件，只需把配置文件中组件的class更换为长连接组件即可。查看文档中“同步客户端”章节。

**Comment by Shandawei** [comment]
好的谢谢
