### ISSUE TITLE
Uncaught mix\exceptions\ErrorException: Undefined index: worker_num

### ISSUE THREAD

**Issue by zhenyangze** [mixstart/mixphp#36]
Hi:
使用composer安装的，在执行service start 中报错。
修改文件： `vendor/mixstart/mixphp-framework/src/http/HttpServer.php:46`行。
将：
```php
$this->server->set($this->setting);
```
修改为：
```php
$this->server->set($this->settings);
```

谢谢。

**Comment by onanying** [comment]
最近国内的 composer 镜像不更新了，导致框架是最新版本，框架核心是上一个版本，不对应，需要切换到国外镜像。
