### ISSUE TITLE
readme typo

### ISSUE THREAD

**Issue by supercent** [mixstart/mixphp#39]
expected:

开发方式几乎与传统 MVC 框架完全一致，用户无需了解 Swoole 即可开始开发。

got instead:

开发方式几乎与传统 MVC 框架完全一至，用户无需了解 Swoole 即可开始开发。

**Comment by supercent** [comment]
不合并，我把这关闭了。抱歉没有理解项目的规则。

> 二八效应，80%的开源项目里80%的代码都是由创始人所写，所以我决定另外那20%也自己来。

**Comment by onanying** [comment]
像这样毫无营养的 PR 我也接受，那让那些花费巨量时间经历提交 PR 的人怎么想？我只接收有贡献的代码

**Comment by supercent** [comment]
@onanying Ok, 谢谢您的时间，打扰了，不好意思呢！

**Comment by supercent** [comment]
那么烦请注明一下，类似拼写错误的低级 PR ，一律不接受。

**Comment by supercent** [comment]
能给你指出错误，说明也是花了时间，认真读了之后，然后才做的 pr，这一点时间，原来是不被尊重的。

**Comment by onanying** [comment]
与尊重无关，搞清楚 issue 与 pr 的用途区别，issue 顺便提，任何问题都可以，pr 是用来提交有价值的代码的。

**Comment by supercent** [comment]
Fine.
