### ISSUE TITLE
建议使用 .gitignore 代替使用 index.html

### ISSUE THREAD

**Issue by krissss** [mixstart/mixphp#5]
我看在目录结构上，您是使用的 `index.html` 来保证目录存在的，当然用 `index.html` 也能保证目录不被用户访问到。但是我觉得使用 `.gitignore` 或许会更好，几点原因：
1. `.` 文件不论是在 linux 还是在 windows，都能很好的隐藏，因为这不是用户关注的文件
2. 比如像 `libray` 这类需要用户保留目录的，可以使用 `.gitkeep` 
3. 比如像 `runtime` 这类不需要保存到 git 版本库的，一定是使用 `.gitignore` 的，及时这里你不加，最终用户也是要加这个的
4. 框架本身就已经限定了用户能访问的目录在 `web\public` 下，所以用户是没有可能直接访问到 `libray` 这类目录的

**Comment by onanying** [comment]
建议很好，已经修改，TKS
