### ISSUE TITLE
composer 版本管理

### ISSUE THREAD

**Issue by krissss** [mixstart/mixphp#6]
> 该建议不代表强烈建议，只是感觉需要权衡考量。

将 `mixphp/mix1` framework 做为 `composer` 的一个包有以下几个好处：
1. 便于版本化，通过 `composer.lock` 文件可以固定当前项目使用的 mix 版本，减少因为版本导致的问题
2. 感觉像当前如果比如我要更新 `mix` 框架，只能下载新的 release 包，然后替换其中的 `mixphp\mix1` 目录
缺点也是有的：
1. 增加了用户使用的门槛，因为确实当前国内对 `composer` 的了解和使用还是有所欠缺的（但我想用户都已经能了解 `swoole` 了，应该不难去学习下 `composer` 的基本用法吧，何况这是趋势所向呢）
2. 其他我没想到的一些困难麻烦吧

**Comment by onanying** [comment]
这个我想过很多次，我还要继续斟酌一下，TKS

**Comment by onanying** [comment]
该建议已经被采纳，`composer create-project mixstart/mixphp --prefer-dist`
