### ISSUE TITLE
Route怎么实现可选参数呢？

### ISSUE THREAD

**Issue by SyanH** [mixstart/mixphp#7]

**Comment by onanying** [comment]
问题描述的不详细，是要在路由加自己的参数吧，看看文档：https://www.kancloud.cn/onanying/mixphp1/379961

**Comment by SyanH** [comment]
加参数这个文档里有，我的意思是加可选参数，就是可以带和不带这个参数都可以匹配到，不带的话会有个默认值

**Comment by onanying** [comment]
正常是没有做这样的功能，不过，参数是正则，patterns 字段内，你使用正则应该可以实现。

**Comment by onanying** [comment]
但是平时做项目，通常我不会设计像你说的这样类型的 url 。

**Comment by onanying** [comment]
我会做两条规则，带参数一条规则，不带的一条规则

**Comment by SyanH** [comment]
好的，谢谢~
框架不错，正在研究使用
